# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/bbaron/workspacec/fineftp-server/example/CMakeLists.txt))

/Users/bbaron/workspacec/fineftp-server/xcodeproj/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.2/bin/cmake -H/Users/bbaron/workspacec/fineftp-server -B/Users/bbaron/workspacec/fineftp-server/xcodeproj
