# Generated by CMake, DO NOT EDIT

TARGETS:= 
empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/bbaron/workspacec/fineftp-server/cmake/Findasio.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/bbaron/workspacec/fineftp-server/cmake/fineftpConfig.cmake.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Users/bbaron/workspacec/fineftp-server/fineftp-server/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CMakePackageConfigHelpers.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/CheckLibraryExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindPackageMessage.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/FindThreads.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/Cellar/cmake/3.17.2/share/cmake/Modules/WriteBasicConfigVersionFile.cmake))

/Users/bbaron/workspacec/fineftp-server/xcodeproj/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/Cellar/cmake/3.17.2/bin/cmake -H/Users/bbaron/workspacec/fineftp-server -B/Users/bbaron/workspacec/fineftp-server/xcodeproj
